##############################
# base deps stage            #
##############################

ARG NODE_VERSION=22
ARG NGINX_VERSION=1.27-alpine

FROM node:${NODE_VERSION}-alpine AS deps
WORKDIR /app

# Install project dependencies
COPY package*.json ./
RUN npm ci

##############################
# build stage                #
##############################

FROM deps AS build
WORKDIR /app

# Copy only the sources Nuxt needs for the static build
COPY app ./app
COPY i18n ./i18n
COPY public ./public
COPY nuxt.config.ts ./
COPY tsconfig.json ./

RUN npm run generate

##############################
# production stage           #
##############################

FROM nginx:${NGINX_VERSION} AS production

# Copy static assets generated by Nuxt
COPY --from=build /app/.output/public /usr/share/nginx/html

# Provide our nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
